### ISSUE TITLE
Can a provenance relationship be demonstrated between model and notebook?

### ISSUE THREAD

**Issue by TheBellman** [LeapBeyond/catwalk#29]
It would be attractive for enterprise users to be able to demonstrate a provable relationship between a version of the source notebook, the exported model, and the final deployable container.

**Comment by andyr0id** [comment]
This is out of scope for Catwalk itself.

In practice, a provenance relationship between notebook, model and image can be acheived with .

Some Catwalk users have adopted a pattern where the model version is contained in the notebook, and `model.{py,yml}` files are treated as build artifacts where this version is written. This sets up a a provenance relationship.
